spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ledger}
    username: ${DB_USERNAME:ledger}
    password: ${DB_PASSWORD:ledger}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
