--liquibase formatted sql

--changeset ledger-engine:001-baseline-schema
--comment: Baseline schema for ledger-engine (no Flyway)
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'account'


CREATE TABLE public.account (
    id bigint NOT NULL,
    full_number character varying(200),
    entity character varying(50),
    type character varying(50),
    sub_type character varying(50),
    main_account character varying(100),
    sub_account character varying(200),
    buffer character varying(50),
    currency character varying(4) NOT NULL,
    ledger_balance numeric(38,18) DEFAULT 0 NOT NULL,
    available_balance numeric(38,18) DEFAULT 0 NOT NULL,
    status character varying(20) NOT NULL,
    allow_negative boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    create_dt timestamp with time zone,
    created_by character varying(100),
    update_dt timestamp with time zone,
    updated_by character varying(100),
    CONSTRAINT ck_account_currency CHECK (((currency)::text ~ '^[A-Z]{2,4}$'::text)),
    CONSTRAINT ck_account_status CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'VERIFIED'::character varying, 'ACTIVE'::character varying, 'DORMANT'::character varying, 'CLOSED'::character varying, 'SUSPENDED'::character varying])::text[])))
);

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.fx_rate (
    id bigint NOT NULL,
    base character varying(4) NOT NULL,
    target character varying(4) NOT NULL,
    rate numeric(32,10) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    create_dt timestamp with time zone,
    created_by character varying(100),
    update_dt timestamp with time zone,
    updated_by character varying(100)
);

ALTER TABLE public.fx_rate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fx_rate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.ledger_entry (
    id bigint NOT NULL,
    txn_id bigint,
    target_id character varying(100),
    amount numeric(38,18) NOT NULL,
    direction character varying(10) NOT NULL,
    currency character varying(4) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    create_dt timestamp with time zone,
    created_by character varying(100),
    update_dt timestamp with time zone,
    updated_by character varying(100),
    CONSTRAINT ck_ledger_entry_amount_positive CHECK ((amount > (0)::numeric)),
    CONSTRAINT ck_ledger_entry_direction CHECK (((direction)::text = ANY ((ARRAY['DEBIT'::character varying, 'CREDIT'::character varying])::text[])))
);

ALTER TABLE public.ledger_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ledger_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.ledger_movement (
    id bigint NOT NULL,
    txn_id bigint,
    alias character varying(100),
    wallet_id bigint NOT NULL,
    originator_id character varying(100),
    target_id character varying(100),
    amount numeric(38,18) NOT NULL,
    currency character varying(4) NOT NULL,
    order_type character varying(30) NOT NULL,
    status character varying(40) NOT NULL,
    remarks text,
    event text,
    metadata text,
    type character varying(20) DEFAULT 'TRANSFER'::character varying NOT NULL,
    payer_context text,
    recipient_context text,
    files text,
    compliance_context text,
    associated_ledger_movement_id bigint,
    movement_key character varying(150) NOT NULL,
    mode character varying(10) DEFAULT 'AUTO'::character varying NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    create_dt timestamp with time zone,
    created_by character varying(100),
    update_dt timestamp with time zone,
    updated_by character varying(100),
    CONSTRAINT ck_movement_amount_positive CHECK ((amount > (0)::numeric)),
    CONSTRAINT ck_movement_mode CHECK (((mode)::text = ANY ((ARRAY['AUTO'::character varying, 'MANUAL'::character varying, 'ALL'::character varying])::text[])))
);

ALTER TABLE public.ledger_movement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ledger_movement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.rule (
    id bigint NOT NULL,
    name character varying(200),
    description character varying(500),
    direction character varying(10),
    multiplier numeric(38,18),
    target_account character varying(200),
    content text,
    is_active boolean DEFAULT true NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    create_dt timestamp with time zone,
    created_by character varying(100),
    update_dt timestamp with time zone,
    updated_by character varying(100)
);

CREATE TABLE public.rule_execution (
    id bigint NOT NULL,
    name character varying(200),
    description character varying(500),
    order_type character varying(30),
    metadata text,
    is_active boolean DEFAULT true NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    create_dt timestamp with time zone,
    created_by character varying(100),
    update_dt timestamp with time zone,
    updated_by character varying(100)
);

ALTER TABLE public.rule_execution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rule_execution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.rule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.system_configuration (
    id bigint NOT NULL,
    name character varying(200),
    target character varying(100),
    scope character varying(100),
    value text,
    is_active boolean DEFAULT true NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    create_dt timestamp with time zone,
    created_by character varying(100),
    update_dt timestamp with time zone,
    updated_by character varying(100)
);

ALTER TABLE public.system_configuration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_configuration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.wallet (
    id bigint NOT NULL,
    account_id bigint NOT NULL,
    alias character varying(100) NOT NULL,
    nickname character varying(200),
    ext_identifier character varying(100),
    ext_type character varying(50),
    hash character varying(66),
    type character varying(20) NOT NULL,
    wallet_type character varying(20),
    status character varying(20) NOT NULL,
    owner_id character varying(100) NOT NULL,
    currency character varying(4) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    create_dt timestamp with time zone,
    created_by character varying(100),
    update_dt timestamp with time zone,
    updated_by character varying(100),
    CONSTRAINT ck_wallet_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'ACTIVE'::character varying, 'DORMANT'::character varying, 'CLOSED'::character varying, 'SUSPENDED'::character varying])::text[]))),
    CONSTRAINT ck_wallet_type CHECK (((wallet_type IS NULL) OR ((wallet_type)::text = ANY ((ARRAY['INDIVIDUAL'::character varying, 'CORPORATE'::character varying])::text[])))),
    CONSTRAINT ck_wallet_type_assoc CHECK (((type)::text = ANY ((ARRAY['CUSTODIAN'::character varying, 'CRYPTO'::character varying])::text[])))
);

ALTER TABLE public.wallet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.fx_rate
    ADD CONSTRAINT fx_rate_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ledger_entry
    ADD CONSTRAINT ledger_entry_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ledger_movement
    ADD CONSTRAINT ledger_movement_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.rule_execution
    ADD CONSTRAINT rule_execution_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.rule
    ADD CONSTRAINT rule_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.system_configuration
    ADD CONSTRAINT system_configuration_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT uk_account_full_number UNIQUE (full_number);

ALTER TABLE ONLY public.ledger_movement
    ADD CONSTRAINT uk_movement_key UNIQUE (movement_key);

ALTER TABLE ONLY public.rule_execution
    ADD CONSTRAINT uk_rule_execution_name UNIQUE (name);

ALTER TABLE ONLY public.wallet
    ADD CONSTRAINT uk_wallet_owner_currency UNIQUE (owner_id, currency);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT uniqueaccountkey UNIQUE (entity, type, sub_type, main_account, sub_account, buffer, currency);

ALTER TABLE ONLY public.wallet
    ADD CONSTRAINT uniquealias UNIQUE (alias);

ALTER TABLE ONLY public.fx_rate
    ADD CONSTRAINT uniquefxratekey UNIQUE (base, target);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT uniquemainaccountsubaccount UNIQUE (main_account, sub_account);

ALTER TABLE ONLY public.system_configuration
    ADD CONSTRAINT uniquetargetandscope UNIQUE (target, scope);

ALTER TABLE ONLY public.wallet
    ADD CONSTRAINT uniquewalletkey UNIQUE (account_id, ext_identifier, type);

ALTER TABLE ONLY public.wallet
    ADD CONSTRAINT wallet_pkey PRIMARY KEY (id);

CREATE INDEX ix_wallet_owner ON public.wallet USING btree (owner_id);

CREATE INDEX ledger_movement_idx_walletid ON public.ledger_movement USING btree (wallet_id);

ALTER TABLE ONLY public.ledger_movement
    ADD CONSTRAINT fk_movement_wallet FOREIGN KEY (wallet_id) REFERENCES public.wallet(id);

ALTER TABLE ONLY public.wallet
    ADD CONSTRAINT fk_wallet_account FOREIGN KEY (account_id) REFERENCES public.account(id);

--rollback DROP TABLE IF EXISTS ledger_movement, ledger_entry, wallet, account, fx_rate, rule, rule_execution, system_configuration CASCADE;
