-- =============================================================================
-- Foundation: product POs ported from the-wallet-ledger (Account, Wallet,
-- LedgerMovement, LedgerEntry) + engine double-entry journal on top.
-- =============================================================================

-- Account (COA + mutable balances) — legacy shape
CREATE TABLE account (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_number         VARCHAR(200),
    entity              VARCHAR(50),
    type                VARCHAR(50),
    sub_type            VARCHAR(50),
    main_account        VARCHAR(100),
    sub_account         VARCHAR(200),
    buffer              VARCHAR(50),
    currency            VARCHAR(4)  NOT NULL,
    ledger_balance      NUMERIC(38,18) NOT NULL DEFAULT 0,
    available_balance   NUMERIC(38,18) NOT NULL DEFAULT 0,
    status              VARCHAR(20) NOT NULL,
    allow_negative      BOOLEAN NOT NULL DEFAULT FALSE,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    version             INT NOT NULL DEFAULT 0,
    create_dt           TIMESTAMP WITH TIME ZONE,
    created_by          VARCHAR(100),
    update_dt           TIMESTAMP WITH TIME ZONE,
    updated_by          VARCHAR(100),
    CONSTRAINT uk_account_full_number UNIQUE (full_number),
    CONSTRAINT uniqueAccountKey UNIQUE (entity, type, sub_type, main_account, sub_account, buffer, currency),
    CONSTRAINT uniqueMainAccountSubAccount UNIQUE (main_account, sub_account),
    CONSTRAINT ck_account_status CHECK (status IN (
        'NEW','VERIFIED','ACTIVE','DORMANT','CLOSED','SUSPENDED'
    )),
    CONSTRAINT ck_account_currency CHECK (currency ~ '^[A-Z]{2,4}$')
);

-- Wallet — legacy shape + owner_id/currency for CRM onboarding
CREATE TABLE wallet (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT NOT NULL,
    alias           VARCHAR(100) NOT NULL,
    nickname        VARCHAR(200),
    ext_identifier  VARCHAR(100),
    ext_type        VARCHAR(50),
    hash            VARCHAR(66),
    type            VARCHAR(20) NOT NULL,
    wallet_type     VARCHAR(20),
    status          VARCHAR(20) NOT NULL,
    owner_id        VARCHAR(100) NOT NULL,
    currency        VARCHAR(4) NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    version         INT NOT NULL DEFAULT 0,
    create_dt       TIMESTAMP WITH TIME ZONE,
    created_by      VARCHAR(100),
    update_dt       TIMESTAMP WITH TIME ZONE,
    updated_by      VARCHAR(100),
    CONSTRAINT fk_wallet_account FOREIGN KEY (account_id) REFERENCES account(id),
    CONSTRAINT uniqueAlias UNIQUE (alias),
    CONSTRAINT uniqueWalletKey UNIQUE (account_id, ext_identifier, type),
    CONSTRAINT uk_wallet_owner_currency UNIQUE (owner_id, currency),
    CONSTRAINT ck_wallet_status CHECK (status IN (
        'PENDING','VERIFIED','ACTIVE','DORMANT','CLOSED','SUSPENDED'
    )),
    CONSTRAINT ck_wallet_type_assoc CHECK (type IN ('CUSTODIAN','CRYPTO')),
    CONSTRAINT ck_wallet_type CHECK (wallet_type IS NULL OR wallet_type IN ('INDIVIDUAL','CORPORATE'))
);

CREATE INDEX ix_wallet_owner ON wallet(owner_id);

-- Ledger movement — legacy business log + engine extensions
CREATE TABLE ledger_movement (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txn_id                          BIGINT,
    alias                           VARCHAR(100),
    wallet_id                       BIGINT NOT NULL,
    originator_id                   VARCHAR(100),
    target_id                       VARCHAR(100),
    amount                          NUMERIC(38,18) NOT NULL,
    currency                        VARCHAR(4) NOT NULL,
    order_type                      VARCHAR(30) NOT NULL,
    status                          VARCHAR(40) NOT NULL,
    remarks                         TEXT,
    event                           TEXT,
    metadata                        TEXT,
    type                            VARCHAR(20) NOT NULL DEFAULT 'TRANSFER',
    payer_context                   TEXT,
    recipient_context               TEXT,
    files                           TEXT,
    compliance_context              TEXT,
    associated_ledger_movement_id   BIGINT,
    movement_key                    VARCHAR(150) NOT NULL,
    mode                            VARCHAR(10) NOT NULL DEFAULT 'AUTO',
    journal_transaction_id          UUID,
    is_active                       BOOLEAN NOT NULL DEFAULT TRUE,
    version                         INT NOT NULL DEFAULT 0,
    create_dt                       TIMESTAMP WITH TIME ZONE,
    created_by                      VARCHAR(100),
    update_dt                       TIMESTAMP WITH TIME ZONE,
    updated_by                      VARCHAR(100),
    CONSTRAINT fk_movement_wallet FOREIGN KEY (wallet_id) REFERENCES wallet(id),
    CONSTRAINT uk_movement_key UNIQUE (movement_key),
    CONSTRAINT ck_movement_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_movement_mode CHECK (mode IN ('AUTO','MANUAL','ALL'))
);

CREATE INDEX ledger_movement_idx_walletId ON ledger_movement(wallet_id);

-- Legacy movement-side entry log (not the double-entry journal)
CREATE TABLE ledger_entry (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txn_id      BIGINT,
    target_id   VARCHAR(100),
    amount      NUMERIC(38,18) NOT NULL,
    direction   VARCHAR(10) NOT NULL,
    currency    VARCHAR(4) NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    version     INT NOT NULL DEFAULT 0,
    create_dt   TIMESTAMP WITH TIME ZONE,
    created_by  VARCHAR(100),
    update_dt   TIMESTAMP WITH TIME ZONE,
    updated_by  VARCHAR(100),
    CONSTRAINT ck_ledger_entry_direction CHECK (direction IN ('DEBIT','CREDIT')),
    CONSTRAINT ck_ledger_entry_amount_positive CHECK (amount > 0)
);

-- =============================================================================
-- New on top: double-entry journal
-- =============================================================================

CREATE TABLE journal_transaction (
    id                  UUID PRIMARY KEY,
    idempotency_key     VARCHAR(150) NOT NULL,
    request_hash        VARCHAR(64) NOT NULL,
    reference           VARCHAR(150),
    description         VARCHAR(500),
    status              VARCHAR(20) NOT NULL,
    effective_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    reversal_of_id      UUID,
    CONSTRAINT uk_transaction_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uk_transaction_reversal_of UNIQUE (reversal_of_id),
    CONSTRAINT fk_transaction_reversal_of FOREIGN KEY (reversal_of_id) REFERENCES journal_transaction(id),
    CONSTRAINT ck_transaction_status CHECK (status IN ('POSTED','REVERSED'))
);

CREATE TABLE journal_entry (
    id                  UUID PRIMARY KEY,
    transaction_id      UUID NOT NULL,
    account_id          BIGINT NOT NULL,
    side                VARCHAR(10) NOT NULL,
    amount              NUMERIC(38,18) NOT NULL,
    currency            VARCHAR(4) NOT NULL,
    sequence_number     INTEGER NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_journal_entry_transaction FOREIGN KEY (transaction_id) REFERENCES journal_transaction(id),
    CONSTRAINT fk_journal_entry_account FOREIGN KEY (account_id) REFERENCES account(id),
    CONSTRAINT uk_entry_transaction_sequence UNIQUE (transaction_id, sequence_number),
    CONSTRAINT ck_journal_entry_side CHECK (side IN ('DEBIT','CREDIT')),
    CONSTRAINT ck_journal_entry_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_journal_entry_currency CHECK (currency ~ '^[A-Z]{2,4}$'),
    CONSTRAINT ck_journal_entry_sequence_positive CHECK (sequence_number > 0)
);

CREATE INDEX ix_journal_entry_account_created ON journal_entry(account_id, created_at, id);
CREATE INDEX ix_journal_entry_transaction ON journal_entry(transaction_id);

ALTER TABLE ledger_movement
    ADD CONSTRAINT fk_movement_journal
    FOREIGN KEY (journal_transaction_id) REFERENCES journal_transaction(id);
