-- Remaining the-wallet-ledger product tables (PO foundation copy).
-- No product redesign yet — schema mirrors legacy entities (standalone IDs / TEXT for json).

CREATE TABLE payment_method (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id               BIGINT,
    type                    VARCHAR(30) NOT NULL,
    status                  VARCHAR(40) NOT NULL,
    metadata                TEXT,
    tokenization_value      VARCHAR(500),
    tokenization_provider   VARCHAR(100),
    hash                    VARCHAR(64),
    is_active               BOOLEAN NOT NULL DEFAULT TRUE,
    version                 INT NOT NULL DEFAULT 0,
    create_dt               TIMESTAMP WITH TIME ZONE,
    created_by              VARCHAR(100),
    update_dt               TIMESTAMP WITH TIME ZONE,
    updated_by              VARCHAR(100)
);
CREATE INDEX payment_method_idx_walletId ON payment_method(wallet_id);

CREATE TABLE virtual_account (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ext_identifier  VARCHAR(100),
    ext_type        VARCHAR(50),
    status          VARCHAR(20) NOT NULL,
    nick_name       VARCHAR(200),
    type            VARCHAR(30),
    metadata        TEXT,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    version         INT NOT NULL DEFAULT 0,
    create_dt       TIMESTAMP WITH TIME ZONE,
    created_by      VARCHAR(100),
    update_dt       TIMESTAMP WITH TIME ZONE,
    updated_by      VARCHAR(100)
);
CREATE INDEX idx_virtual_account_ext_identifier ON virtual_account(ext_identifier);

CREATE TABLE virtual_sub_account (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency            VARCHAR(4) NOT NULL,
    status              VARCHAR(20) NOT NULL,
    ledger_balance      NUMERIC(38,18) NOT NULL DEFAULT 0,
    available_balance   NUMERIC(38,18) NOT NULL DEFAULT 0,
    virtual_account_id  BIGINT,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    version             INT NOT NULL DEFAULT 0,
    create_dt           TIMESTAMP WITH TIME ZONE,
    created_by          VARCHAR(100),
    update_dt           TIMESTAMP WITH TIME ZONE,
    updated_by          VARCHAR(100),
    CONSTRAINT fk_vsa_va FOREIGN KEY (virtual_account_id) REFERENCES virtual_account(id)
);

CREATE TABLE virtual_account_application (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status              VARCHAR(30) NOT NULL,
    type                VARCHAR(30),
    ext_identifier      VARCHAR(100),
    ext_type            VARCHAR(50),
    remark              VARCHAR(500),
    metadata            TEXT,
    virtual_account_id  BIGINT,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    version             INT NOT NULL DEFAULT 0,
    create_dt           TIMESTAMP WITH TIME ZONE,
    created_by          VARCHAR(100),
    update_dt           TIMESTAMP WITH TIME ZONE,
    updated_by          VARCHAR(100),
    CONSTRAINT fk_vaa_va FOREIGN KEY (virtual_account_id) REFERENCES virtual_account(id)
);

CREATE TABLE wallet_application (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ext_identifier  VARCHAR(100),
    ext_type        VARCHAR(50),
    request_body    TEXT,
    reference_hash  VARCHAR(128),
    status          VARCHAR(20) NOT NULL,
    fail_counter    INT DEFAULT 0,
    alias           VARCHAR(100),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    version         INT NOT NULL DEFAULT 0,
    create_dt       TIMESTAMP WITH TIME ZONE,
    created_by      VARCHAR(100),
    update_dt       TIMESTAMP WITH TIME ZONE,
    updated_by      VARCHAR(100),
    CONSTRAINT uniqueWalletApplication UNIQUE (reference_hash)
);

CREATE TABLE recipient (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT,
    transfer_channel    VARCHAR(20),
    status              VARCHAR(20) NOT NULL,
    metadata            TEXT,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    version             INT NOT NULL DEFAULT 0,
    create_dt           TIMESTAMP WITH TIME ZONE,
    created_by          VARCHAR(100),
    update_dt           TIMESTAMP WITH TIME ZONE,
    updated_by          VARCHAR(100)
);

CREATE TABLE linked_bank_account (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT,
    status      VARCHAR(20) NOT NULL,
    metadata    TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    version     INT NOT NULL DEFAULT 0,
    create_dt   TIMESTAMP WITH TIME ZONE,
    created_by  VARCHAR(100),
    update_dt   TIMESTAMP WITH TIME ZONE,
    updated_by  VARCHAR(100)
);

CREATE TABLE fx_rate (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base        VARCHAR(4) NOT NULL,
    target      VARCHAR(4) NOT NULL,
    rate        NUMERIC(32,10) NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    version     INT NOT NULL DEFAULT 0,
    create_dt   TIMESTAMP WITH TIME ZONE,
    created_by  VARCHAR(100),
    update_dt   TIMESTAMP WITH TIME ZONE,
    updated_by  VARCHAR(100),
    CONSTRAINT uniqueFxRateKey UNIQUE (base, target)
);

CREATE TABLE rule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(200),
    description     VARCHAR(500),
    direction       VARCHAR(10),
    multiplier      NUMERIC(38,18),
    target_account  VARCHAR(200),
    content         TEXT,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    version         INT NOT NULL DEFAULT 0,
    create_dt       TIMESTAMP WITH TIME ZONE,
    created_by      VARCHAR(100),
    update_dt       TIMESTAMP WITH TIME ZONE,
    updated_by      VARCHAR(100)
);

CREATE TABLE rule_execution (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200),
    description VARCHAR(500),
    order_type  VARCHAR(30),
    metadata    TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    version     INT NOT NULL DEFAULT 0,
    create_dt   TIMESTAMP WITH TIME ZONE,
    created_by  VARCHAR(100),
    update_dt   TIMESTAMP WITH TIME ZONE,
    updated_by  VARCHAR(100),
    CONSTRAINT uk_rule_execution_name UNIQUE (name)
);

CREATE TABLE system_configuration (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200),
    target      VARCHAR(100),
    scope       VARCHAR(100),
    "value"     TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    version     INT NOT NULL DEFAULT 0,
    create_dt   TIMESTAMP WITH TIME ZONE,
    created_by  VARCHAR(100),
    update_dt   TIMESTAMP WITH TIME ZONE,
    updated_by  VARCHAR(100),
    CONSTRAINT uniqueTargetAndScope UNIQUE (target, scope)
);
